version: '3.8'
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host_prod:5432/db_prod
      - SPRING_DATASOURCE_USERNAME=user_prod
      - SPRING_DATASOURCE_PASSWORD=senha_prod
