version: '3.8'
services:
  api:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=qa
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host_qa:5432/db_qa
      - SPRING_DATASOURCE_USERNAME=user_qa
      - SPRING_DATASOURCE_PASSWORD=senha_qa
