version: "3.9"

services:
  db:
    image: postgres:15
    container_name: meu_postgres_local
    environment:
      POSTGRES_USER: hydrocore
      POSTGRES_PASSWORD: segundoano
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge

volumes:
  postgres_data:
