name: Deploy em dash to Render QA

on:
  pull_request:
    types: [labeled]

jobs:
  deploy:
    if: contains(github.event.label.name, 'deploy-qa')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Trigger Render QA Deploy
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d "{\"branch\":\"${{ github.head_ref }}\"}" \
            https://api.render.com/v1/services/srv-d2hjn5q4d50c739g1ejg/deploys
